version: '2.2'

services:
  db:
    container_name: dbmv_db
    image: mariadb:10.7.8
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root

  app:
    container_name: dbmv_web
    build:
      context: .
      dockerfile: ./docker-development/Dockerfile
    command: sh ./entrypoints/docker-entrypoint.sh
    depends_on:
      - db
    ports:
      - "3080:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_PASSWORD: root
      DATABASE_HOST: db
      DATABASE_PORT: 3306
volumes:
  gem_cache:
  bundle:
